"use client";

import Link from "next/link";

const LAST_UPDATED = "July 1, 2025";
const CONTACT_EMAIL = "legal@qued.in";
const COMPANY_NAME = "Qued";
const WEBSITE = "qued.in";

const sections = [
  {
    id: "acceptance",
    title: "1. Acceptance of Terms",
    text: `By creating an account or using ${WEBSITE}, you agree to these Terms of Service and our Privacy Policy. If you do not agree, do not use the platform. These terms apply to all users — Free, Pro, and Max.`,
  },
  {
    id: "eligibility",
    title: "2. Eligibility",
    bullets: [
      "You must be at least 17 years old to use Qued.",
      "You must be a student or professional preparing for interviews — Qued is not intended for automated scraping or competitive intelligence gathering.",
      "You may not create accounts on behalf of others or share your account credentials.",
      "Corporate accounts and institutional access are only permitted if explicitly agreed in writing with Qued.",
    ],
  },
  {
    id: "plans",
    title: "3. Plans & Payments",
    content: [
      {
        subtitle: "Free Plan",
        text: "The Free plan (₹0/forever) gives you 3 mock interview sessions per month, 3 DSA problem submissions per day, and basic scoring. No credit card required.",
      },
      {
        subtitle: "Pro Plan — ₹299/month",
        text: "Unlimited mock sessions, 8 questions per session, model answers, company-specific prep, unlimited DSA, Skill Passport, and follow-up questions.",
      },
      {
        subtitle: "Max Plan — ₹699/month",
        text: "Everything in Pro plus 11 questions per session, Resume/Project Discussion prep, Cheat Sheet, Personal Coach Agent, DSA solution access, and the ability to re-answer questions on your report.",
      },
      {
        subtitle: "Billing",
        text: "Subscriptions are billed monthly. Payments are processed by Razorpay. By subscribing, you authorise Razorpay to charge your payment method on a recurring monthly basis until you cancel.",
      },
      {
        subtitle: "Cancellation & Refunds",
        text: "You may cancel at any time from your account settings. Your plan stays active until the end of the current billing period. We do not offer prorated refunds for unused days. If a technical failure on our side prevented access to paid features, contact us and we will evaluate the case individually.",
      },
      {
        subtitle: "Plan Changes",
        text: "Upgrading takes effect immediately. Downgrading takes effect at the start of your next billing cycle. We reserve the right to change plan pricing with 30 days' notice to existing subscribers.",
      },
    ],
  },
  {
    id: "acceptable-use",
    title: "4. Acceptable Use",
    bullets: [
      "Do not submit code designed to harm or overload our execution environment — including fork bombs, infinite loops, filesystem access attempts, or network calls from the code editor",
      "Do not extract questions, model answers, or coaching content in bulk for redistribution or resale",
      "Do not use automated scripts or bots to interact with the platform in place of real human use",
      "Do not reverse-engineer or attempt to access our source code or proprietary AI prompts",
      "Do not impersonate another user, student, or recruiter on the platform",
      "Do not use Qued to prepare for fraudulent interviews — i.e., impersonating another candidate in an actual company hiring process",
      "Do not share your account with others or create multiple accounts to circumvent Free plan limits",
    ],
  },
  {
    id: "ai-disclaimer",
    title: "5. AI-Generated Content Disclaimer",
    text: `All scores, feedback, coaching reports, model answers, and cheat sheets on ${COMPANY_NAME} are generated by AI (Claude by Anthropic). This content is for practice and self-improvement only. ${COMPANY_NAME} does not guarantee that AI feedback reflects the assessment criteria of any specific company or recruiter. Interview outcomes depend on many factors outside our control. We are a preparation tool, not a predictor of results.`,
  },
  {
    id: "content-ownership",
    title: "6. Your Content",
    content: [
      {
        subtitle: "You own your answers",
        text: "The interview answers, voice recordings, and code you submit remain yours. You grant Qued a limited licence to process this content to generate your scores and feedback. We do not use your individual answers to train AI models.",
      },
      {
        subtitle: "Aggregate improvements",
        text: "We may use anonymised, aggregated data (e.g. which topics students struggle with most) to improve the question bank and platform. No individual answer or transcript is attributable to you in this process.",
      },
    ],
  },
  {
    id: "platform-content",
    title: "7. Platform Content",
    text: `The question bank, model answers, coaching frameworks, Skill Passport scoring rubrics, and all other platform content are owned by ${COMPANY_NAME}. You may use this content for personal interview preparation only. You may not reproduce, redistribute, publish, or resell any part of it without written permission.`,
  },
  {
    id: "availability",
    title: "8. Service Availability",
    bullets: [
      "We aim for high availability but do not guarantee uninterrupted access. Maintenance, infrastructure failures, or third-party outages (Anthropic API, Razorpay) may cause temporary downtime.",
      "We will communicate planned maintenance in advance where possible.",
      "Plan usage limits (e.g. 3 sessions/month on Free) reset on the 1st of each calendar month at midnight IST.",
      "We reserve the right to suspend or terminate accounts that violate these terms without prior notice.",
    ],
  },
  {
    id: "limitation",
    title: "9. Limitation of Liability",
    text: `To the maximum extent permitted by Indian law, ${COMPANY_NAME} is not liable for: indirect or consequential damages from use of the platform; loss of employment opportunities or interview outcomes; inaccuracies in AI-generated feedback; or data loss due to user error. Our total liability for any claim shall not exceed the amount you paid us in the 3 months preceding the claim.`,
  },
  {
    id: "governing-law",
    title: "10. Governing Law",
    text: `These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts of India. We will first attempt to resolve disputes through good-faith negotiation before pursuing legal action.`,
  },
  {
    id: "changes",
    title: "11. Changes to These Terms",
    text: `We may update these Terms as the platform evolves. We will notify you via email at least 7 days before material changes take effect. Continued use after that date constitutes acceptance of the revised terms.`,
  },
  {
    id: "contact",
    title: "12. Contact",
    text: `Questions about these Terms? Email us at ${CONTACT_EMAIL}. We respond within 5 business days.`,
  },
];

export default function TermsPage() {
  return (
    <main className="min-h-screen" style={{ background: "#FFFDF0", color: "#111111" }}>

      <style>{`
        .legal-header { padding: 48px 24px 40px; }
        .legal-container { max-width: 760px; margin: 0 auto; padding: 0 16px; }
        .legal-toc { padding: 20px; margin-bottom: 44px; }
        .legal-section { margin-bottom: 44px; }
        .legal-h1 { font-size: clamp(28px, 6vw, 52px); font-weight: 900; letter-spacing: -1.5px; line-height: 1.05; margin: 0 0 14px; }
        .legal-h2 { font-size: 20px; font-weight: 800; letter-spacing: -0.4px; margin: 0 0 16px; padding-bottom: 10px; border-bottom: 2px solid #111111; display: inline-block; }
        .legal-body { font-size: 15px; line-height: 1.75; color: #333; margin: 12px 0 0; }
        .legal-sub { margin-top: 14px; padding-left: 14px; border-left: 3px solid #E5E7EB; }
        .legal-sub-label { font-size: 12px; font-weight: 700; letter-spacing: 0.04em; text-transform: uppercase; color: #111; margin: 0 0 5px; }
        .legal-bullet { display: flex; gap: 10px; align-items: flex-start; margin-bottom: 10px; font-size: 15px; line-height: 1.65; color: #333; }
        .legal-dot { flex-shrink: 0; margin-top: 8px; width: 6px; height: 6px; border-radius: 50%; background: #111111; display: inline-block; }
        .legal-cta { background: #111111; color: white; border-radius: 14px; padding: 28px 28px; margin-top: 12px; }
        .legal-crosslinks { display: grid; grid-template-columns: 1fr 1fr; gap: 14px; margin-bottom: 28px; }
        .legal-crosslink { display: block; background: white; border: 1px solid #E5E7EB; border-radius: 12px; padding: 18px 20px; text-decoration: none; color: #111; }
        .legal-pill-dark { display: inline-block; background: #111111; color: #FFD600; font-size: 10px; font-weight: 800; letter-spacing: 0.1em; text-transform: uppercase; padding: 3px 9px; border-radius: 4px; margin-bottom: 14px; }

        @media (max-width: 600px) {
          .legal-header { padding: 36px 16px 28px; }
          .legal-container { padding: 0 16px; }
          .legal-toc { padding: 16px; }
          .legal-h2 { font-size: 18px; }
          .legal-body { font-size: 14px; }
          .legal-bullet { font-size: 14px; }
          .legal-cta { padding: 22px 20px; border-radius: 12px; }
          .legal-crosslinks { grid-template-columns: 1fr; }
        }
      `}</style>

      {/* Header */}
      <div style={{ borderBottom: "1px solid #E5E7EB" }}>
        <div className="legal-container">
          <div className="legal-header">
            <Link
              href="/"
              style={{
                display: "inline-block",
                marginBottom: 24,
                fontSize: 12,
                fontWeight: 600,
                color: "#111",
                textDecoration: "none",
                letterSpacing: "0.05em",
                textTransform: "uppercase",
                opacity: 0.45,
              }}
            >
              ← Qued
            </Link>

            <div className="legal-pill-dark">Legal</div>

            <h1 className="legal-h1">Terms of Service</h1>

            <p style={{ fontSize: 14, color: "#777", margin: "0 0 10px" }}>
              Last updated: {LAST_UPDATED}
            </p>
            <p className="legal-body" style={{ margin: 0, maxWidth: 580 }}>
              The rules for using {COMPANY_NAME}. Written to be readable. Short
              version: use the platform honestly, don't abuse the code runner,
              and we'll keep building for you.
            </p>
          </div>
        </div>
      </div>

      {/* Body */}
      <div className="legal-container" style={{ paddingTop: 36, paddingBottom: 80 }}>

        {/* TOC */}
        <nav
          className="legal-toc"
          style={{ background: "white", border: "1px solid #E5E7EB", borderRadius: 12 }}
        >
          <p style={{ fontSize: 10, fontWeight: 700, letterSpacing: "0.1em", textTransform: "uppercase", color: "#aaa", margin: "0 0 12px" }}>
            Contents
          </p>
          {sections.map((s) => (
            <div key={s.id} style={{ marginBottom: 5 }}>
              <a
                href={`#${s.id}`}
                style={{ fontSize: 14, color: "#111", textDecoration: "none", fontWeight: 500 }}
                onMouseEnter={(e) => (e.currentTarget.style.textDecoration = "underline")}
                onMouseLeave={(e) => (e.currentTarget.style.textDecoration = "none")}
              >
                {s.title}
              </a>
            </div>
          ))}
        </nav>

        {/* Sections */}
        {sections.map((section) => (
          <section key={section.id} id={section.id} className="legal-section">
            <h2 className="legal-h2">{section.title}</h2>

            {"text" in section && section.text && (
              <p className="legal-body">{section.text}</p>
            )}

            {"bullets" in section && section.bullets && (
              <ul style={{ margin: "12px 0 0", padding: 0, listStyle: "none" }}>
                {section.bullets.map((b, i) => (
                  <li key={i} className="legal-bullet">
                    <span className="legal-dot" />
                    {b}
                  </li>
                ))}
              </ul>
            )}

            {"content" in section &&
              section.content &&
              section.content.map((item, i) => (
                <div key={i} className="legal-sub" style={{ marginTop: i === 0 ? 12 : 20 }}>
                  <p className="legal-sub-label">{item.subtitle}</p>
                  <p className="legal-body" style={{ margin: 0 }}>{item.text}</p>
                </div>
              ))}
          </section>
        ))}

        {/* Cross-links */}
        <div className="legal-crosslinks">
          <Link href="/privacy" className="legal-crosslink">
            <p style={{ fontSize: 10, fontWeight: 700, letterSpacing: "0.08em", textTransform: "uppercase", color: "#aaa", margin: "0 0 5px" }}>Also read</p>
            <p style={{ fontSize: 15, fontWeight: 700, margin: 0 }}>Privacy Policy →</p>
          </Link>
          <Link href="/contact" className="legal-crosslink">
            <p style={{ fontSize: 10, fontWeight: 700, letterSpacing: "0.08em", textTransform: "uppercase", color: "#aaa", margin: "0 0 5px" }}>Get in touch</p>
            <p style={{ fontSize: 15, fontWeight: 700, margin: 0 }}>Contact us →</p>
          </Link>
        </div>

        {/* CTA */}
        <div className="legal-cta">
          <p style={{ fontSize: 11, fontWeight: 700, letterSpacing: "0.08em", textTransform: "uppercase", color: "#FFD600", margin: "0 0 8px" }}>
            Questions about these terms?
          </p>
          <p style={{ fontSize: 14, lineHeight: 1.7, margin: "0 0 18px", color: "#bbb" }}>
            If anything is unclear, reach out before assuming the worst.
          </p>
          <a
            href={`mailto:${CONTACT_EMAIL}`}
            style={{
              display: "inline-block",
              background: "#FFD600",
              color: "#111",
              fontWeight: 800,
              fontSize: 14,
              padding: "9px 18px",
              borderRadius: 8,
              textDecoration: "none",
            }}
          >
            {CONTACT_EMAIL}
          </a>
        </div>
      </div>
    </main>
  );
}